package creditcard.gui.concrete;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ButtonGroup;

import creditcard.CreditCardModule;
import creditcard.account.info.CreditCardHolder;
import framework.account.IAccount;
import framework.account.ModelChangeListener;

public class CreditCardDialog extends javax.swing.JDialog {
	CreditCardModule factory = null;

	public CreditCardDialog(CreditCardModule factory) {
		this.factory = factory;

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		// {{INIT_CONTROLS
		setTitle("Add personal account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(283, 303);
		setVisible(false);
		JRadioButtonGold.setText("Gold");
		JRadioButtonGold.setActionCommand("0");
		getContentPane().add(JRadioButtonGold);
		JRadioButtonGold.setBounds(36, 0, 84, 24);
		JRadioButtonSilver.setText("Silver");
		JRadioButtonSilver.setActionCommand("1");
		getContentPane().add(JRadioButtonSilver);
		JRadioButtonSilver.setBounds(36, 24, 84, 24);

		JRadioButtonBronze.setText("Bronze");
		JRadioButtonBronze.setActionCommand("2");
		getContentPane().add(JRadioButtonBronze);
		JRadioButtonBronze.setBounds(36, 48, 84, 24);
		
		ButtonGroup group = new ButtonGroup();
	    group.add(JRadioButtonGold);
	    group.add(JRadioButtonSilver);
	    group.add(JRadioButtonBronze);
		
		
		JLabel1.setText("Name");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(java.awt.Color.black);
		JLabel1.setBounds(12, 84, 48, 24);
		JLabel2.setText("Street");
		getContentPane().add(JLabel2);
		JLabel2.setForeground(java.awt.Color.black);
		JLabel2.setBounds(12, 108, 48, 24);
		JLabel3.setText("City");
		getContentPane().add(JLabel3);
		JLabel3.setForeground(java.awt.Color.black);
		JLabel3.setBounds(12, 132, 48, 24);
		JLabel4.setText("State");
		getContentPane().add(JLabel4);
		JLabel4.setForeground(java.awt.Color.black);
		JLabel4.setBounds(12, 156, 48, 24);
		JLabel5.setText("Zip");
		getContentPane().add(JLabel5);
		JLabel5.setForeground(java.awt.Color.black);
		JLabel5.setBounds(12, 180, 48, 24);
		JLabel7.setText("Email");
		getContentPane().add(JLabel7);
		JLabel7.setForeground(java.awt.Color.black);
		JLabel7.setBounds(12, 228, 48, 24);
		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(84, 84, 156, 20);
		getContentPane().add(JTextField_CT);
		JTextField_CT.setBounds(84, 132, 156, 20);
		getContentPane().add(JTextField_ST);
		JTextField_ST.setBounds(84, 156, 156, 20);
		getContentPane().add(JTextField_STR);
		JTextField_STR.setBounds(84, 108, 156, 20);
		getContentPane().add(JTextField_ZIP);
		JTextField_ZIP.setBounds(84, 180, 156, 20);
		getContentPane().add(JTextField_EM);
		JTextField_EM.setBounds(84, 228, 156, 20);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48, 264, 84, 24);
		JButton_Cancel.setText("Cancel");
		JButton_Cancel.setActionCommand("Cancel");
		getContentPane().add(JButton_Cancel);
		JButton_Cancel.setBounds(156, 264, 84, 24);

		JButton_OK.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				int accountType = 0; // checking
				if(JRadioButtonGold.isSelected()) {
					accountType = 0;
				} else if(JRadioButtonSilver.isSelected()) {
					accountType = 1;
				} else if(JRadioButtonBronze.isSelected()) {
					accountType = 2;
				}
				String name=JTextField_NAME.getText(); String
				street=JTextField_STR.getText(); String city=JTextField_CT.getText();
				String zipCode=JTextField_ZIP.getText(); String state=JTextField_ST.getText();
				String email = JTextField_EM.getText();
				CreditCardHolder customer = factory.getCreditCardHolderFactory().createCreditCardHolder(name);
				customer.setAddress(street,city,state,zipCode,"US",email);
				IAccount acc = customer.createAccount(1, 0, accountType);
				acc.addModelChangeListener(new ModelChangeListener<IAccount>() {
					
					@Override
					public void changed(IAccount x) {
						factory.getAccountListFactory().getAccountList().notifyModelChange();
					}
				});
				factory.getAccountListFactory().getAccountList().add(acc);
				dispose();
				
			}
			
		});
		JButton_Cancel.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
	}

	javax.swing.JRadioButton JRadioButtonGold = new javax.swing.JRadioButton();
	javax.swing.JRadioButton JRadioButtonSilver = new javax.swing.JRadioButton();
	javax.swing.JRadioButton JRadioButtonBronze = new javax.swing.JRadioButton();
	
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel3 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel4 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel5 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel6 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel7 = new javax.swing.JLabel();
	javax.swing.JTextField JTextField_NAME = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_CT = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_ST = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_STR = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_ZIP = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_EM = new javax.swing.JTextField();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();
	javax.swing.JButton JButton_Cancel = new javax.swing.JButton();
	javax.swing.JLabel JLabel8 = new javax.swing.JLabel();

}
